name: Build Debian package

on: ['push', 'pull_request']

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt update;
        sudo DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cython3 build-essential python3 python3-venv python3-build debhelper-compat pybuild-plugin-pyproject python3-all-dev python3-numpy;
    - name: Build package
      run: make deb
